### ISSUE TITLE
gmail support in firefox?

### ISSUE THREAD

**Issue by dlethin** [amazingmarvin/amazingmarvin-browserextension#18]
This is a great extension.  Thanks.  Simplifies some of my workflow. 

I had a question about Firefox and gmail integration support - Is it supposed to work?   The extension is available in the store, and the description suggests tasks from gmail works, but when I see the README in this repo there's a TODO item for firefox support.

However, in my Firefox with this extension installed I don't see the Marvin Icon in in my list of emails or when i click on an individual email.  This does work for me with Google Chrome.     Is there perhaps some specific firefox setting I might have that could be causing this? Not sure where to look.  Other functionality for creating tasks from browser tabs works fine.

Thanks.

**Comment by rijavecb** [comment]
Hi @dlethin. Thank you for letting us know about this issue. I just gave Gmail integration a try, and it should work in Firefox too. However, you might have to give it permissions to read the page first. Do you see this message when you open Gmail and then hover over the Marvin button in the extensions list:

![image](https://github.com/amazingmarvin/amazingmarvin-browserextension/assets/15850530/1ac33f8c-5ff3-496a-b539-6e41eea8765b)

After I give it permissions, the button showed up and worked when I clicked on it:

![image](https://github.com/amazingmarvin/amazingmarvin-browserextension/assets/15850530/a86ee8d1-dbf2-47ea-92fd-8902d1697f65)

I think you should be able to "fix" this but right-clicking on the extension and allowing it to read and change data on mail.google.com

![image](https://github.com/amazingmarvin/amazingmarvin-browserextension/assets/15850530/c2d8d561-9f7c-47ef-bf73-e97d2b97278d)

Could you give that a try and let me know if it worked?

I'm really sorry for the super late reply, I just saw this yesterday when I got a notification about another issue.

**Comment by dlethin** [comment]
No worries on the late reply -- I'm grateful for the help.  That was indeed the issue.  I must have missed that this step was necessary and I now see how I can right-click to always allow this.
This feature if very helpful.   Much more convenient then forwarding emails to my custom AM email address, which is what I was doing when I was accessing email through the mac mail app.

Happy holidays!

**Comment by rijavecb** [comment]
Thank you for letting me know that fixed the issue! I'm happy to hear that the "Add to Marvin" button works now :)

Happy holidays!
